name: aspen_builder
version: 0.4.0
description: A modern, easy-to-use asset packer (builder package)
homepage: https://github.com/refi64/aspen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  aspen: ^0.4.0
  build: ^2.0.1
  csslib: ^0.17.0
  source_gen: ^1.0.0
  base85: ^1.0.3

dev_dependencies:
  pedantic: ^1.9.0

dependency_overrides:
  aspen:
    path: ../aspen
  base85:
    path: ../base85
