name: aspen_assets
version: 0.4.0
description: A modern, easy-to-use asset packer (assets package)
homepage: https://github.com/refi64/aspen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aspen: ^0.4.0
  base85: ^1.0.3

dependency_overrides:
  aspen:
    path: ../aspen
  base85:
    git:
      url: git@github.com:iRebbok/base85.git
      ref: null-safety

dev_dependencies:
  pedantic: ^1.9.0
